version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      # c'est ici que les données factices que j'ai ajoutées lorsque j'exécutais l'application localement résident
      - ./data:/data/db
    ports:
      - "27017:27017"